name: "Continuous Integration"

on: [push, pull_request]

jobs:
  test:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
          tools: "composer:v2"
          coverage: "xdebug"

      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest --no-interaction"

      - name: "Run unit test suite"
        run: "composer test-unit-coverage"

      - name: "Run integration test suite"
        run: "composer test-integration"

  finish:
    name: "Coverage"
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: "Merge intermediate results and finalize Coveralls report"
        uses: coverallsapp/github-action@master
        with:
          format: clover
          github-token: ${{ secrets.GITHUB_TOKEN }}
