name: "Continuous Integration"

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - 'src/**'
      - 'test/**'
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - 'src/**'
      - 'test/**'

jobs:
  test:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "8.0"
          tools: "composer:v2"
          coverage: "xdebug"

      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest --no-interaction"

      - name: "Run unit test suite"
        run: "composer test-unit-coverage"

      - name: "Run integration test suite"
        run: "composer test-integration"

      - name: "Upload coverage report to Coveralls"
        uses: coverallsapp/github-action@v2
        with:
          file: clover.xml
          github-token: ${{ secrets.GITHUB_TOKEN }}
